### ISSUE TITLE
Change to use built-in GeoCoordinate class instead of MapLocation

### ISSUE THREAD

**Issue by rshackleton** [liamgold/map-location-form-component#3]
Could be worth changing to use the built-in GeoCoordinate class instead of MapLocation:

https://docs.microsoft.com/en-us/dotnet/api/system.device.location.geocoordinate?view=netframework-4.8

**Comment by liamgold** [comment]
Good call @rshackleton, thanks for the recommendation.

I'll change it locally and give it a test before pushing another version to nuget 👍
